### ISSUE TITLE
Make the appliance console file a class that we can run

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-gems-pending#12]
Right now the console is a big script which is run when it is required.

We would rather make it a class or module that has a `.run` method which can take parameters instead of relying on environment variables such as `RAILS_ROOT`.

**Comment by carbonin** [comment]
In general we would like to make the whole `appliance_console` directory look more like a gem to prepare to move it into its own repo.

**Comment by Fryguy** [comment]
@miq-bot move_issue manageiq-appliance_console
