### ISSUE TITLE
FYI, you may have to re-record cassettes with psych 2.1.0+

### ISSUE THREAD

**Issue by jerryk55** [ManageIQ/manageiq-gems-pending#345]
See https://github.com/ghempton/camcorder/issues/13.  Already fixed for miq_disk_spec.rb in the Fine branch.

**Comment by JPrause** [comment]
@jerryk55 is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.
