### ISSUE TITLE
Move MiqFileStorage into core and provider specific gems

### ISSUE THREAD

**Issue by NickLaMuro** [ManageIQ/manageiq-gems-pending#403]
Related to the large issue, https://github.com/ManageIQ/manageiq-gems-pending/issues/231 (the `mount/*` checkbox), though has grown in scope since that issue was created do to the addition of the following classes/libs being created/reworked:

- `lib/gems/pending/util/miq_file_storage.rb`
- `lib/gems/pending/util/miq_object_storage.rb`
- `lib/gems/pending/util/miq_ftp_lib.rb`
- `lib/gems/pending/util/object_storage/*.rb`
  - `miq_ftp_storage.rb`
  - `miq_s3_storage.rb`
  - `miq_swift_storage.rb`

Really, this is all `manageiq` related, and should just live there in `lib/` (or a core gem... if we ever go that route).  The provider specific ones should live in their respective provider repos, and get loaded in as part of the rake tasks to determine what functionality is available then (instead of the hard coding that is done currently).

Task items
----------

* [ ] Move into "core" ( https://github.com/ManageIQ/manageiq/pull/19547 , https://github.com/ManageIQ/manageiq-gems-pending/pull/454 )
* [ ] Create a plugin system for providers
* [ ] Extract provider code to their respective repos

**Comment by NickLaMuro** [comment]
Updated full file list of files to be extracted (see PR description):

- `lib/miq_file_storage.rb`
- `lib/miq_ftp_lib.rb`
- `lib/miq_object_storage.rb`
- `lib/mount/*.rb`
	* `lib/mount/miq_generic_mount_session.rb`
	* `lib/mount/miq_glusterfs_session.rb`
	* `lib/mount/miq_local_mount_session.rb`
	* `lib/mount/miq_nfs_session.rb`
	* `lib/mount/miq_smb_session.rb`
- `lib/object_storage/*.rb`
	* `lib/object_storage/miq_ftp_storage.rb`
	* `lib/object_storage/miq_s3_storage.rb`
	* `lib/object_storage/miq_swift_storage.rb`
- `spec/lib/miq_file_storage_spec.rb`
- `spec/lib/miq_ftp_lib_spec.rb`
- `spec/lib/miq_object_storage_spec.rb`
- `spec/lib/mount/miq_generic_mount_session_spec.rb`
- `spec/lib/mount/miq_local_mount_session_spec.rb`
- `spec/lib/object_storage/miq_ftp_storage_spec.rb`
- `spec/lib/object_storage/miq_s3_storage_spec.rb`
- `spec/lib/object_storage/miq_swift_storage_spec.rb`
- `spec/support/custom_matchers/exist_on_ftp_server.rb`
- `spec/support/custom_matchers/have_size_on_ftp_server_of.rb`
- `spec/support/examples_group/generated_tmp_files.rb`
- `spec/support/examples_group/with_ftp_server.rb`

**Comment by NickLaMuro** [comment]
Note:  This will most likely just be removed/deleted, as we are moving away from supporting the process of connecting to file storage providers, and leaving that up to the user to mount it themselves.

**Comment by Fryguy** [comment]
Did you want to keep this issue open anyway, or should we just close?

**Comment by NickLaMuro** [comment]
@Fryguy I think I am going to leave it open until we delete it, and then close it.  But if you think I might forget (which... honestly, I might), we can also close it now.  I just wanted something open as a reminder that it needed to be updated.
