### ISSUE TITLE
Extract PostgresAdmin into a separate gem

### ISSUE THREAD

**Issue by NickLaMuro** [ManageIQ/manageiq-gems-pending#404]
This is still an idea in it's infancy that has only been briefly discussed by @carbonin and myself (possibly in other forms).  This is mostly a follow up to some discussion surrounding https://github.com/ManageIQ/manageiq-gems-pending/pull/385 and how that was implemented.

TODOs
------

- [ ] Remove appliance based backup from `PostgresAdmin` restore specs
  - Added in https://github.com/ManageIQ/manageiq-gems-pending/pull/385 (see PR for details)
- [ ] Remove any references to `ActiveRecord` if they exist in `PostgresAdmin` (shouldn't, but we just want to rely on `pg` only
- [ ] Remove `awesome-spawn` dependency?
  - Mostly using it's command builder for this, and most of our execution is happening through `Open3` or other stdlib methods.
  - Unsure if we actually want to do this, but it would make this a little more focused on the `Postgresql` aspect of this gem, but up for discussion.
- [ ] Roll in a few features that exist in `manageiq-appliance_console`, and have that call out to this
  - The database configuration stuff that is done there could be useful in this lib
- [ ] Make a wrapper class in `manageiq` for handling our specific issues
  - I assume ideally we would have an easy enough to deal with DSL that would allow this to be pretty small.  Maybe even only need a config file?
- [ ] Make "said gem"

Updated thoughts: Looking at this again a few weeks later, I think the changes to the specs could possibly be done as part of creating the new gem, and possibly skipped being done here.  Speaking personally, I might wait for the dust to settle on hammer before trying to tackle any of this, but we will see.

**Comment by NickLaMuro** [comment]
cc @carbonin

**Comment by Fryguy** [comment]
@NickLaMuro Can this be closed now since the direction is to move to appliance console (via #516 )?

**Comment by NickLaMuro** [comment]
@Fryguy woops, missed the ping on this, but stumbled across it when looking for a different PR.

But absolutely, will do.
