### ISSUE TITLE
Can MiqProcess be dropped completely in favor of sys-proctable?

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-gems-pending#459]
@NickLaMuro asked the question over at https://github.com/ManageIQ/manageiq-gems-pending/pull/458#discussion_r371317219 as to whether or not we can drop `MiqProcess` completely in favor of sys-proctable.

I've created this issue to see if I can do a method by method comparison of how it would be done. I'm pretty sure most of it can.

**Comment by djberg96** [comment]
`MiqProcess.get_active_process_by_name(process_name)` (source: `https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/miq-process.rb#L9`)

The sys-proctable equivalent:

`Sys::ProcTable.ps.find_all{ |process| process.name == name }`

Comments: The Windows code looks broken to me. It's collecting handles for some reason, which are not pids, but are the Windows equivalent of a file descriptor.

**Comment by djberg96** [comment]
`MiqProcess.linux_process_stat(pid = nil)`

Source: https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/miq-process.rb#L24

The sys-proctable gem already collects information out of `/proc/<pid>/stat`, as well as several other files, so all of those fields are available as methods on the resulting proctable struct, e.g.` process.pid`, `process.ppid`, and so on. So, nothing special needs to be done here.

**Comment by djberg96** [comment]
`MiqProcess.processInfo(pid = nil)`

Source: https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/miq-process.rb#L84

All of the information that method collects is available within the data returned by sys-proctable. There are some calculations happening here, so those would have to be emulated.

**Comment by djberg96** [comment]
`MiqProcess.command_line(pid)`

Source: https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/miq-process.rb#L130

The sys-proctable equivalent:

`Sys::ProcTable.ps(pid).try(:cmdline) || ""`

Comments: The underlying implementation is the equivalent code I pasted above.

**Comment by djberg96** [comment]
`MiqProcess.alive?(pid)`

Source: https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/miq-process.rb#L136

You don't need sys-proctable for his, the current implementation is sufficient.

Comments: I'm not sure why there's a Windows check there. It should work on any platform.

**Comment by djberg96** [comment]
`MiqProcess.is_worker?(pid)`

https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/miq-process.rb#L147

The sys-proctable equivalent would essentially be the same.

**Comment by djberg96** [comment]
`MiqProcess..process_list_all(wmi = nil)`

Source: https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/miq-process.rb#L152

The sys-proctable equivalent is just:

`Sys::ProcTable.ps`

Comments: No special consideration for Windows is required, it's already baked in.

**Comment by djberg96** [comment]
`MiqProcess.process_list_wmi(wmi = nil, pid = nil)`

Source: https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/miq-process.rb#L167

Comments: This will require some special work for Windows because, in addition to process information, it's doing another query to collect performance data.

**Comment by djberg96** [comment]
`MiqProcess.process_list_linux(cmd_str, skip_header = false)`

https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/miq-process.rb#L195

Comments: Other than the custom calculations, nothing else special has to happen on Linux.

**Comment by NickLaMuro** [comment]
@djberg96 Looking at what you have so far, and looking at the last method you posted above, `process_list_linux`, this seems to only be used internally for this method:

https://github.com/search?q=org%3AManageIQ+process_list_linux&type=Code

And the only two callers of that are:

* `processInfo`:  https://github.com/search?q=org%3AManageIQ+processInfo&type=Code
* `process_list_all`: https://github.com/search?q=org%3AManageIQ+process_list_all&type=Code

The former being used a bit more than the latter.

**Comment by NickLaMuro** [comment]
Looking at `process_list_all`, it seems it is used in one place:  `Vm#running_processes`

This basically needs the following:

- "pid"
- "memory_usage"
- "memory_size"
- "percent_memory"
- "percent_cpu"
- "cpu_time"
- "priority"
- "operating_system_id"

https://github.com/ManageIQ/manageiq-schema/blob/07c4e867573be3472744568a9222b25a466f7a57/db/migrate/20130923182042_collapsed_initial_migration.rb#L2395-L2407

Though, it does need to support Windows vms it seems.

**Comment by djberg96** [comment]
`MiqProcess.parse_process_data(data_type, pinfo, perf = nil, os = nil)`

Source: https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/miq-process.rb#L209

Comments: There are some custom calculations happening here, but it looks to me like most of those could happen inline with whatever uses sys-proctable.

**Comment by djberg96** [comment]
`MiqProcess.str_time_to_sec(time_str)`

Source: https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/miq-process.rb#L234

Comments: Just an internal helper method that should probably be private. I wonder if active_support already has something like this, though.

**Comment by djberg96** [comment]
`MiqProcess.suspend_process(pid)` and `MiqProcess.resume_process(pid)`

The sys-proctable gem does not support this.

Comments: These appear to be dead code, as the method used in the Windows version no longer exists, and Unix was never supported. It *could* be supported for unixy flavors using the `proc-wait3` gem (author: me) via the `Process.pause` option if you want.

For Windows it's possible, but I would have to see if there's a library out there that already does this. Otherwise we would have to implement it.

**Comment by djberg96** [comment]
> Though, it does need to support Windows vms it seems.

Not only that, it looks like it's ONLY used on Windows. For connecting to Windows from Linux, it appears we're using a command called "wmic" in conjunction with "winexe".

**Comment by djberg96** [comment]
To get processes on a remote system, we would have to use ssh. This *could* be theoretically done by using the authentications table if linked to the vm (or ems).

**Comment by djberg96** [comment]
Closing, a decent chunk was moved over, I leave the rest up to others.
