### ISSUE TITLE
Add missing features to appliance_console_cli

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-gems-pending#54]
https://bugzilla.redhat.com/show_bug.cgi?id=1385697 was opened to request adding features to the `appliance_console_cli` that are currently only available in the interactive console.

It will be easier to add things here in a check list and track each missing feature separately.
Please add to this list if I missed any.

- [ ] evmserverd operations (https://github.com/ManageIQ/manageiq-gems-pending/pull/53)
- [x] Log file disk configuration (https://github.com/ManageIQ/manageiq-gems-pending/pull/52)
- [ ] Log rotation configuration
- [ ] Database HA
  - [ ] Create standby
  - [ ] Create primary
  - [ ] Start failover monitor
- [ ] Database maintenance
- [ ] SCAP
- [ ] Network config
  - [ ] DHCP
  - [ ] Static
  - [ ] Test network config
- [x] Set timezone
- [ ] Set date and time
- [ ] Database restore

**Comment by Fryguy** [comment]
@miq-bot move_issue manageiq-appliance_console
